// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: marks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const create_Marks = `-- name: Create_Marks :one
INSERT INTO marks (id, created_at, updated_at, title, tag, url, user_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, created_at, updated_at, title, tag, url, user_id
`

type Create_MarksParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
	Tag       string
	Url       string
	UserID    pgtype.UUID
}

func (q *Queries) Create_Marks(ctx context.Context, arg Create_MarksParams) (Mark, error) {
	row := q.db.QueryRow(ctx, create_Marks,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Title,
		arg.Tag,
		arg.Url,
		arg.UserID,
	)
	var i Mark
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Tag,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
