POST http://localhost:3003/api/marks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhdmlkIiwiaWQiOiI2NGY1ZjAxMGQ5NmZiZmFjOTYxMTE4ZTMiLCJpYXQiOjE2OTUyMzY1MjN9.x4kxWJtg-a_Ky93EUP8I1cJ-nj3EpAroYGsVBryQ8nI

{
"title": "MIDDELWARE USER EXTRACTION 1001",
"tag": "Michael Chan",
"url": "https://reactpatterns.com/"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "David",
    "password": "987456123"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "David",
    "password": "987456123"
}

###

POST http://localhost:3003/api/comments
Content-Type: application/json

{
    "content": "Testing endPoint"
}

###

GET http://localhost:3003/api/comments